stages:
- stage: estadoA 
  displayName: estadoAA
  jobs:
    - job: jobaA
      displayName: Jovb
      pool:
         vmImage: 'windows-2019' 
    - job: JOBBBB
      displayName: job2
      pool:
        vmImage: 'windows-2019'
      steps:
      - task: 
        inputs:
          powershell: 'echo Write your commands here.' 
          #workingDirectory: # Optional
          #failOnStderr: false # Optional