stages:
- stage: estadoA 
  displayName: estadoAA
  jobs:
    - job: jobaA
      displayName: Jovb
      script: 'echo Write your commands here.'
      pool:
         vmImage: 'windows-2019' 
    - job: JOBBBB
      displayName: job2
      pool:
        vmImage: 'windows-2019'
