          stages:
- stage: estadoA 
  displayName: estadoAA
  jobs:
    - job: jobaA
      displayName: Jovb
      pool:
         vmImage: 'windows-2019' 
    - job: JOBBBB
      displayName: job2
      pool:
        vmImage: 'windows-2019'
      steps:
      - powershell: Write-Host Hello $(name)
      displayName: Say hello
      name: firstStep
      workingDirectory: $(build.sourcesDirectory)
      failOnStderr: true
      env:
         name: Microsoft

